### ISSUE TITLE
Migrate to Spring Boot 3.1

### ISSUE THREAD

**Issue by nanotaboada** [nanotaboada/java.samples.spring.boot#44]
- https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide
- https://docs.openrewrite.org/recipes/java/spring/boot3/upgradespringboot_3_0
- https://spring.io/blog/2023/05/18/spring-boot-3-1-0-available-now/

**Comment by Shiroo77** [comment]
Hello, My name is Prem and I would like to work on this issue ! Can I ?

**Comment by nanotaboada** [comment]
Absolutely!
